name: Deploy EliteWalk to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/EliteWalk-12

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing client dependencies..."
            cd client
            npm install
            npm run build

            echo "Restarting frontend..."
            pm2 delete EliteWalk-client || true
            pm2 serve build 3000 --name EliteWalk-client --spa

            echo "Installing server dependencies..."
            cd ../server
            npm install

            echo "Restarting backend..."
            pm2 restart EliteWalk-12-server || pm2 start npm --name EliteWalk-12-server -- start

            pm2 save
